In [53]:
import pandas as pd
import matplotlib.pyplot as plt # для визуализации
import numpy as np # для операций с массивами
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

#import torch as T
device = 'cpu'

In [54]:
print("Создадим данные")

x = np.array([
     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32) # входные значения 

y = np.array([1, 1, 1, 0, 0, 0], dtype=np.long) # выходные значения

Создадим данные


In [55]:
x

array([[1.5, 2.5],
       [3.5, 4.5],
       [6.5, 6.5],
       [4.5, 1.5],
       [5.5, 3.5],
       [7.5, 5.5]], dtype=float32)

In [56]:
y

array([1, 1, 1, 0, 0, 0])

In [57]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [58]:
model.fit(x, y) 

LogisticRegression(random_state=0, solver='liblinear')

.fit() возвращает экземпляр модели

In [59]:
LogisticRegression( 
    C=1.0, 
    class_weight=None, 
    dual=False, 
    
    fit_intercept=True,
    intercept_scaling=1, 
    l1_ratio=None, 
    
    max_iter=100,
    multi_class='warn', 
    n_jobs=None, 
    
    penalty='l2',
    random_state=0, 
    solver='liblinear', 
    tol=0.0001, 
    verbose=0,
    warm_start=False
)

LogisticRegression(multi_class='warn', random_state=0, solver='liblinear')

In [60]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x, y)

In [61]:
#model.classes_
model.intercept_ # значение наклона

array([0.11528403])

In [62]:
model.coef_ # точка пересечения

array([[-0.82568302,  0.9325228 ]])

In [63]:
# Оценка модели
model.predict_proba(x)

array([[0.23004334, 0.76995666],
       [0.194388  , 0.805612  ],
       [0.30794535, 0.69205465],
       [0.90038461, 0.09961539],
       [0.76172185, 0.23827815],
       [0.72080602, 0.27919398]])

In [64]:
model.predict(x)

array([1, 1, 1, 0, 0, 0])

In [65]:
model.score(x, y)

1.0

In [66]:
confusion_matrix(y, model.predict(x))

array([[3, 0],
       [0, 3]], dtype=int64)

In [67]:
print(classification_report(y, model.predict(x)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         3

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6

